name: pubtrends_datasets
channels:
  - defaults
  - conda-forge
dependencies:
  - parameterized=0.9.0
  - pip=25.3
  - flask=3.1.2
  - flasgger=0.9.7.1
  - requests=2.32.5
  - coverage=7.11.0
  - dacite=1.8.1
  - GEOparse=2.0.4
